global:
  rate: 1000
  duration: 180
  limit_cpu: 100m
  limit_memory: 128Mi

values:
  - paththrough-aggregator:
      workflow: aggregator
  - paththrough-fluentbit-only:
      workflow: fluentbit-only
  - paththrough-fluentd-only:
      workflow: fluentd-only
  - spin-fluentbit:
      workflow: fluentbit-only
      rate: 1
      rate: 300
  - spin-fluentd:
      workflow: fluentd-only
      rate: 1
  - config-parse-fluentbit-only:
      workflow: fluentbit-only
  - config-parse-fluentd-only:
      workflow: fluentd-only
  - avro-fluentd-only:
      workflow: fluentd-only
  - grep-fluentd-only:
      workflow: fluentd-only
  - grep-fluentbit-only:
      workflow: fluentbit-only
  - flush60-fluentd-only:
      workflow: fluentd-only
  - flush50m-fluentbit-only:
      workflow: fluentbit-only
  - file-buffer-fluentd-only:
      workflow: fluentd-only
  - file-buffer-fluentbit-only:
      workflow: fluentbit-only
  - k8s-fluentbit-only:
      workflow: fluentbit-only
